# -*- coding: utf-8 -*-
"""UAS_BIOTEKNOLOGI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9CTEgYnZsDE6D0V6_n_jXXTFP-d_biQ
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

def network(y, t):
    # create container
    dydt = np.empty(3)

    # set parameters
    V1max = 5.0
    Km1 = 2.0
    Ki = 3.0
    X = 10.0
    k2 = 1.0
    k3 = 0.8
    k4 = 0.3

    # set dynamic variables
    A = y[0]
    B = y[1]
    P = y[2]

    # reaction rates
    v1 = (V1max * X) / ((Km1 + X) * (1 + P / Ki))
    v2 = k2 * A
    v3 = k3 * B
    v4 = k4 * A

    # differential equations
    dydt[0] = v1 - v2 - v4
    dydt[1] = v2 - v3
    dydt[2] = v3

    return dydt

# set initial condition
init = [0, 0, 0]

# set time
t = np.linspace(0, 48, 500)

# run simulation
solution = odeint(network, init, t)

# plot simulation
plt.plot(t, solution[:, 0], label='Metabolite A')
plt.plot(t, solution[:, 1], label='Metabolite B')
plt.plot(t, solution[:, 2], label='Product P')

plt.xlabel('Time (hours)')
plt.ylabel('Concentration')
plt.title('Kinetic Simulation of Metabolic Network')
plt.legend()
plt.grid(True)
plt.show()